# -*- coding: utf-8 -*-
"""Data_Augmentation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tMZGbKqRemrxPELu1JG4mFzrLWGEU0E3

#Drive access
"""

"""#1. Load data"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import librosa
import matplotlib.pyplot as plt
import librosa.display
import csv
import pandas as pd
import os

# %matplotlib inline

#실제 실험 오디오에서 추출한 오디오가 있는 폴더 경로
dominant = 'Drone_audio_ps2_2'
dataDir = '/home/stealthdrone/Desktop/dataset/' + dominant
csvPath = '/home/stealthdrone/Desktop/csv/' + dominant + '.csv'
SR = 44100
switch = 3

"""#Choose your augmentation function
*  switch == 1 : ts
*  switch == 2 : ps1
*  switch == 3 : ps2
"""

def load_audio_file(file_path):
    data = librosa.core.load(file_path, sr = SR)[0] #, sr=44100

    return data

def time_stretch(y):
    data = []
    data.append(librosa.effects.time_stretch(y, 0.81))
    data.append(librosa.effects.time_stretch(y, 0.93))
    data.append(librosa.effects.time_stretch(y, 1.07))
    data.append(librosa.effects.time_stretch(y, 1.23))

    return data

def pitch1_shift(y):
    data = []
    data.append(librosa.effects.pitch_shift(y, SR, n_steps=-2))
    data.append(librosa.effects.pitch_shift(y, SR, n_steps=-1))
    data.append(librosa.effects.pitch_shift(y, SR, n_steps=1))
    data.append(librosa.effects.pitch_shift(y, SR, n_steps=2))
    
    return data

def pitch2_shift(y, step=0):
    data = []
    data.append(librosa.effects.pitch_shift(y, SR, n_steps=-3.5))
    data.append(librosa.effects.pitch_shift(y, SR, n_steps=-2.5))
    data.append(librosa.effects.pitch_shift(y, SR, n_steps=2.5))
    data.append(librosa.effects.pitch_shift(y, SR, n_steps=3.5))

    return data

def save_newfile(y, name, label):
    #change this path to yours
    path = dataDir

    ts_nickname = ['ts_1', 'ts_2', 'ts_3','ts_4']
    ps1_nickname = ['ps1_1', 'ps1_2', 'ps1_3', 'ps1_4']
    ps2_nickname = ['ps2_1', 'ps2_2', 'ps2_3', 'ps2_4']

    if(switch == 1): 
        nickname = ts_nickname
    elif(switch == 2):
        nickname = ps1_nickname
    else:
        nickname = ps2_nickname

    f = open(csvPath, 'a', encoding='utf-8', newline='')
    wr = csv.writer(f)

    for i in range(4):
        filename = nickname[i] + '_' + name
        librosa.output.write_wav(path + "/" + filename + ".wav", y[i], SR)
        wr.writerow([filename, label])

    f.close()

#data dir iteration
metadata = pd.read_csv(csvPath, sep=",")
metadata = metadata.sort_values(by=['filename'])
metadata = metadata.reset_index(drop=True)
metadata

fileList = np.sort(np.array([x.split(".wav") for x in os.listdir(dataDir)])[:,0])

fileDic = dict([(fileList[x],x) for x in range(len(fileList))])

for i in os.listdir(dataDir):
    try:
        name = i.split(".wav")[0]
        location = fileDic[name]
        print(name)
        ##1. load
        y = load_audio_file(dataDir + "/" + i)

        ##2. augment
        if(switch == 1):  
            data = time_stretch(y)
        elif(switch == 2):
            data = pitch1_shift(y)
        else: ##switch == 3
            data = pitch2_shift(y)

        ##3. save changes  
        sound_type = metadata.loc[location]["class"]
        save_newfile(data, name, sound_type) #save_newfile(y, name, label)
        
    except:
        continue

