# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wjznvEAc6c3Z3bgh_JItTuOrvN84gJfy
"""

import numpy as np
import matplotlib.pyplot as plt

def make_time(x):
  arr = []

  for i in range(len(x)):
    arr.append(i * 0.1)

  return arr

#3-2
x_3_2 = [4,4,4,5,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,1,1,0,1,1,1,1,0,1,0,0,0,0,0,0,0,1,1,0,0,0,0]

#4-1
x_4_1 = [0,0,0,0,0,0,0,0,0,0,0,5,5,0,0,0,0,5,0,5,0,5,5,5,5,5,5,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,2,4,4]

#4-2
x_4_2 = [5,4,4,4,5,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,0,0,1,0,1,0]

#6-4
x_6_4 = [5,5,5,5,5,4,5,5,5,4,5,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,5,5,5,5,5,4,5,4,4,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,3,5,3,3,5,5,3,5,3,3,3,3,3,3,5,2,3,2,2,3,2,2,3,3,3,3,3,3,3,3,3,3,3,3,3,3,2,3,3,3,3,3,2,3,3,3,3,3,3,3,3,3]

x = x_4_2[:70]
y = make_time(x)

H, xedges, yedges = np.histogram2d(x, y, bins=(6,len(y)), range = [[0, 6], [0, len(y)*0.1]])
H.shape, xedges.shape, yedges.shape

extent = [yedges[0], yedges[-1], xedges[-1], xedges[0]]
plt.imshow(H, extent=extent, interpolation='nearest')
plt.xlabel('Time (sec)')
plt.ylabel('Class')
plt.savefig('test.png')

# plt.colorbar()
# plt.show()

